apiVersion: v1
kind: Service
metadata:
  name: petstore
  labels:
    app: petstore
  annotations:
spec:
  type: ClusterIP
  selector:
    app: petstore
  ports:
  - name: http
    port: 80
    targetPort: 8080
