metadata:
  name: k8s-argocd
  namespace: lk-argocd
  labels: {}
  annotations: {}
spec:
  origin_servers:
    - k8s_service:
        service_name: argocd-server.lk-argocd
        site_locator:
          site:
            tenant: f5-cz-guwmuexg
            namespace: system
            name: lk-swan-ba
        vk8s_networks: {}
      labels: {}
  no_tls: {}
  port: 80
  same_as_endpoint_port: {}
  healthcheck: []
  loadbalancer_algorithm: LB_OVERRIDE
  endpoint_selection: LOCAL_PREFERRED
